### ISSUE TITLE
Desire to specify number of bytes that should be parsed into a Vec

### ISSUE THREAD

**Issue by BroderickCarlin** [chifflier/nom-derive#1]
Let me first start off by saying this crate looks immensely useful and well written. 

One of my initial observations though is that a lot of the structs that I need to parse can contain either multiple byte arrays or values that exist after a byte array. Lets take a quick look at this toy example that illustrates where this crate fails to build a useful parser: 
```
#[derive(Nom, Debug)]
struct SimpleStruct {
    b_length: u8,
    b: Vec<u8>,
    c: u8,
}
```

One possible solution for this may be something such as the following:
```
#[derive(Nom, Debug)]
struct SimpleStruct {
    a_length: u8,
    #[Length="a_length"]
    a: Vec<u8>,
    a: u8,
}
```

Since it doesn't usually make sense to explicitly record the Vec length in the struct it may even make more sense to to something like the following to indicate that the byte array is preceded by a u8 that dictates it's length.
```
#[derive(Nom, Debug)]
struct SimpleStruct {
    #[Length="u8"]
    a: Vec<u8>,
    a: u8,
}
```

One thing to also consider in all this is if there should be a way to parse a byte array of a known length. for example:
```
#[derive(Nom, Debug)]
struct SimpleStruct {
    #[Length="42"]
    a: Vec<u8>,
    a: u8,
}
```

**Comment by chifflier** [comment]
There is a workaround, even if not satisfying: you can give the parser using the `Parse` attribute:
```rust
#[derive(Nom, Debug)]
struct SimpleStruct {
    b_length: u8,
    #[Parse="count!(be_u8, b_length as usize)"]
    b: Vec<u8>,
    c: u8,
}
```

Even if it works, that's not entirely satisfying because it can quickly require many annotations.

I'll think of more attributes, for ex `#[Count(x)` or `#[Length(y)]` to call the nom matching combinators.

PS: I'm moving this repo to https://github.com/rust-bakery/nom-derive, can you use it for future bug reports ? thanks

**Comment by BroderickCarlin** [comment]
This was resolved in commit https://github.com/rust-bakery/nom-derive/commit/c10684355a99d1cda61885bff361ddbda05cb468  on the new repo
